version: 2.1

jobs:
  build-rom:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Set up Git configuration"
          command: |
            git config --global user.email "diamondguys256x@gmail.com"
            git config --global user.name "NoNameBuilder"
      - run:
          name: "Install required tools"
          command: |
            sudo apt-get update && sudo apt-get install -y \
              python3 curl unzip git repo ccache openjdk-11-jdk
      - run:
          name: "Initialize repo"
          command: |
            repo init -u https://github.com/Evolution-X/manifest -b vic
      - run:
          name: "Sync repo"
          command: |
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: "Pull additional repositories"
          command: |
            # Existing repositories
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_xiaomi_zircon device/xiaomi/zircon
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_xiaomi_zircon-miuicamera device/xiaomi/zircon-miuicamera
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886 kernel/xiaomi/mt6886
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886-modules kernel/xiaomi/mt6886-modules
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886 -b lineage-22.0-dtbo dtbo

            # Missing repositories
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon vendor/xiaomi/zircon
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon-firmware vendor/xiaomi/zircon-firmware
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon-miuicamera vendor/xiaomi/zircon-miuicamera
      - run:
          name: "Set up build environment"
          command: |
            export USE_CCACHE=1
            export CCACHE_DIR=~/.ccache
            export CCACHE_EXEC=/usr/bin/ccache
            ccache -M 50G
      - run:
          name: "Lunch device configuration"
          command: |
            . build/envsetup.sh
            lunch lineage_zircon-ap3a-userdebug
      - run:
          name: "Start ROM build"
          command: |
            m evolution

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-rom
