version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-rom:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install repo tool"
          command: |
            sudo apt-get update
            sudo apt-get install -y repo
      - run:
          name: "Initialize repo"
          command: |
            repo init -u https://github.com/Evolution-X/manifest -b vic --git-lfs
      - run:
          name: "Sync repo"
          command: |
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: "Pull MIUI Camera"
          command: |
            git clone https://github.com/zircon-development/android_device_xiaomi_zircon-miuicamera $(pwd)/device/xiaomi/zircon/miuicamera
      - run:
          name: "Pull Kernel Source"
          command: |
            git clone https://github.com/zircon-development/android_kernel_xiaomi_mt6886 $(pwd)/kernel/xiaomi/mt6886
      - run:
          name: "Pull Sepolicy Vendor"
          command: |
            git clone https://github.com/zircon-development/android_device_mediatek_sepolicy_vndr $(pwd)/device/mediatek/sepolicy_vndr
      - run:
          name: "Pull Kernel Modules"
          command: |
            git clone https://github.com/zircon-development/android_kernel_xiaomi_mt6886-modules $(pwd)/kernel/xiaomi/mt6886-modules
      - run:
          name: "Pull proprietary_vendor_xiaomi_zircon"
          command: |
            git clone https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon $(pwd)/vendor/xiaomi/zircon
      - run:
          name: "Set up build environment"
          command: |
            . build/envsetup.sh
      - run:
          name: "Lunch the device"
          command: |
            lunch lineage_zircon-ap3a-userdebug
      - run:
          name: "Build the ROM"
          command: |
            m evolution

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build-rom:
          requires:
            - say-hello
