version: 2.1

jobs:
  build-rom:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
              gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev \
              lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python-is-python3 \
              bc ccache libstdc++6 ninja-build
      - run:
          name: "Configure Git"
          command: |
            git config --global user.email "diamondguys256x@gmail.com"
            git config --global user.name "NoNameBuilder"
      - run:
          name: "Install repo command"
          command: |
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH=~/bin:$PATH
      - run:
          name: "Sync ROM sources"
          command: |
            repo init -u https://github.com/Evolution-X/manifest -b vic --git-lfs
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: "Pull additional repositories"
          command: |
            git clone https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon vendor/xiaomi/zircon
            git clone https://github.com/zircon-development/android_device_xiaomi_zircon-miuicamera device/xiaomi/zircon-miuicamera
            git clone https://github.com/zircon-development/android_kernel_xiaomi_mt6886 kernel/xiaomi/mt6886
            git clone https://github.com/zircon-development/android_device_mediatek_se
