version: 2.1

jobs:
  build-rom:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Set up Git configuration"
          command: |
            git config --global user.email "insert-email"
            git config --global user.name "insert-your-github-name"
      - run:
          name: "Install required tools"
          command: |
            sudo apt-get update && sudo apt-get install -y \
              python3 curl unzip git repo ccache openjdk-11-jdk
      - run:
          name: "Initialize repo"
          command: |
            repo init -u https://github.com/Evolution-X/manifest -b vic
      - run:
          name: "Force clean repo sync"
          command: |
            repo forall -c 'git reset --hard && git clean -fdx'
            repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
            repo sync -j1 --fail-fast --force-sync --no-clone-bundle --no-tags
      - run:
          name: "Pull additional repositories"
          command: |
            # Device, kernel, and vendor repositories
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_xiaomi_zircon device/xiaomi/zircon
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_xiaomi_zircon-miuicamera device/xiaomi/zircon-miuicamera
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886 kernel/xiaomi/mt6886
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886-modules kernel/xiaomi/mt6886-modules
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr
            git clone --depth=1 --progress --verbose https://github.com/zircon-development/android_kernel_xiaomi_mt6886 -b lineage-22.0-dtbo dtbo

            # Missing repositories
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon vendor/xiaomi/zircon
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon-firmware vendor/xiaomi/zircon-firmware
            git clone --depth=1 --progress --verbose https://git.mainlining.org/zircon-development/proprietary_vendor_xiaomi_zircon-miuicamera vendor/xiaomi/zircon-miuicamera
            git clone https://github.com/xiaomi-mediatek-devs/android_hardware_mediatek -b lineage-22.0 ./hardware/mediatek
            git clone https://github.com/xiaomi-mediatek-devs/android_hardware_xiaomi -b lineage-22.0 ./hardware/xiaomi
      - run:
          name: "Set up build environment and start build"
          command: |
            export USE_CCACHE=1
            export CCACHE_DIR=~/.ccache
            export CCACHE_EXEC=/usr/bin/ccache
            ccache -M 50G

            # Set up environment
            . build/envsetup.sh

            # Lunch device configuration
            lunch lineage_zircon-ap3a-userdebug

            # Start Evolution X build
            make evolution -j$(nproc --all)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-rom
